
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  qr_flutter: ^4.1.0
  uuid: ^4.5.3
  local_auth: ^3.0.0
  flutter_secure_storage: ^10.0.0
  excel: ^4.0.6
  file_picker: ^10.3.10
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.7+1

flutter:
  uses-material-design: true
